### PR TITLE
Texas_SWRA117D_2.4GHz.kicad_mod added

### PR DESCRIPTION
**Pull request by alitekin2fx**
small_size_2 4g_pcb_antenna

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Closing only to re-open so that the auto checking scripts run

**Comment by SchrodingersGat** [comment]
## Naming

As this is the first PR in this library, we need to work out the naming. Refer to the [KiCad Library Convention](https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention#3-symbol-names). 

I would suggest a naming like:

`Texas_SWRA117D_2.4GHz.kicad_mod`

## Keepout

Unfortunately there is not yet an integral method for specifying a keepout in a footprint. I would suggest using a cross + outline on the Drawings layer such as this:

screenshot from 2017-07-03 20-57-25

## KLC

Please look at the [KLC issues raised by our automated checker scripts](https://travis-ci.org/KiCad/RF_Antennas.pretty/builds/249584378)

**Comment by SchrodingersGat** [comment]
If any of the KLC issues do not make sense please ask :)

**Comment by alitekin2fx** [comment]
Okay, i'm going to check :)

**Comment by alitekin2fx** [comment]
I would set the footprint type as virtual, but Travis insists on changing it to through hole due to pin 2 has a plated hole. Any advise?

**Comment by poeschlr** [comment]
As long as you state a good reason why travis gives a warning you can ignore it. (I think virtual is correct here but i'm not sure how we can teach travis to know this. Maybe different setup for this repo?)

**Comment by SchrodingersGat** [comment]
We could change the rule slightly, such that if the footprint is set to *virtual* then it gives a warning but not an error. We can still see the warning messages but it doesn't give a "fail" message.

**Comment by alitekin2fx** [comment]
I think warning message would be a great solution. Then i can change it to virtual again.

**Pull request closed without merging**
