### PR TITLE
Add Johansen 0868AT43A0020 868Mhz chip antenna

### PR DESCRIPTION
**Pull request by MatthewStephenson**
Footprint for Johansen 0868AT43A0020 868Mhz chip antenna

Datasheet: https://www.johansontechnology.com/datasheets/antennas/0868AT43A0020.pdf

image

I have also created (not included in this PR) a version of the footprint with the recommended spiral PCB trace from the datasheet. Should I add this version too?

image

As always, comments and suggestions welcome :)

### CODE REVIEW

**Comment by jkriege2** [comment]
please add a pin1-marker on F.Fab AND F.SilkS ... as done for other parts (here are some non-representative examples):
2017-10-11 20_28_38-footprint editor no active library
2017-08-21 21_16_01-footprint editor no active library
2017-03-11 17_19_53-footprint editor no active library

**Comment by MatthewStephenson** [comment]
Updated the F.Fab with a cut corner - the F.SilkS layer already had an extended line - is that not the right way to do it?

image

**Comment by poeschlr** [comment]
Closing and reopening this for testing purposes. (New KLC scripts)

**Comment by jkriege2** [comment]
Could you adopt the style used for the diodes? I.e. have an open rectangle surrounding the pin1-pad and open for the pin2?

2017-03-11 17_19_53-footprint editor no active library

**Comment by MatthewStephenson** [comment]
Updated silkscreen style as requested:

image

**Comment by jkriege2** [comment]
Hi @MatthewStephenson the footpritn looks good to me. I would merge it in this state. I think having in additiona (as separate footprint) the spiral would be great! If you push it into this branch, I will merge both ...

Best,
JAN

**Comment by MatthewStephenson** [comment]
How about these? I realised versions with both "handedness" are needed as you can't flip footprints without changing the layer.

image

image

**Comment by jkriege2** [comment]
Looks good ... I spotted one thing: the antenna tail should be covered by varnish, i.e. no uncovered copper, right? To achieve this, please rmeove the mask and Paste-layers from the pads for the tail:
2017-11-05 11_50_15-footprint editor no active library

Then the footprint will look like this on the PCB:
2017-11-05 11_50_50-3d viewer

Best,
JAN

**Comment by jkriege2** [comment]
maybe you could also move the REFDES closer to the actual package, i.e. just above the package: 
2017-11-05 11_55_04-footprint editor no active library

Then the REFDES is closer to the actual component on the final PCB.

Best,
JAN

**Comment by MatthewStephenson** [comment]
Made the requested changes. Thanks for taking the time to explain these things - it must have taken you longer to do the screenshots than just to fix it yourself! But I'm happy for the education.

image

**Comment by SchrodingersGat** [comment]
Hi @MatthewStephenson   apologies for the inconvenience but we have marked this repository as read-only as we transition to the new repository for the v5 release.

Please resubmit this pull request to https://github.com/kicad/kicad-footprints

**Pull request closed without merging**
